# Exercises

## 1. Create a vector, scalar, matrix and tensor with values of your choosing using tf.constant()

In [2]:
# Imports
import tensorflow as tf
import numpy as np

In [4]:
# Create values
scalar = tf.constant(3)
vector = tf.constant([1, 2])
matrix = tf.constant([[1, 2],
                      [3, 4]])
tensor = tf.constant(np.random.random(size=50))
scalar, vector, matrix, tensor

(<tf.Tensor: shape=(), dtype=int32, numpy=3>,
 <tf.Tensor: shape=(2,), dtype=int32, numpy=array([1, 2], dtype=int32)>,
 <tf.Tensor: shape=(2, 2), dtype=int32, numpy=
 array([[1, 2],
        [3, 4]], dtype=int32)>,
 <tf.Tensor: shape=(50,), dtype=float64, numpy=
 array([0.27206704, 0.10411592, 0.14081564, 0.93146858, 0.90691601,
        0.48043995, 0.05006621, 0.55660317, 0.67346872, 0.29552004,
        0.16028247, 0.10253821, 0.86205328, 0.04469307, 0.86394224,
        0.14781953, 0.22272567, 0.825571  , 0.98791604, 0.96386657,
        0.55855748, 0.44287839, 0.49889448, 0.39767924, 0.76185468,
        0.2746856 , 0.59636628, 0.09890846, 0.08952617, 0.04105226,
        0.13074706, 0.13090809, 0.37877106, 0.00708217, 0.98446885,
        0.26037977, 0.78607811, 0.98990891, 0.08212901, 0.16204303,
        0.25774126, 0.7202288 , 0.09546568, 0.30937007, 0.98203567,
        0.87459975, 0.45272192, 0.00410526, 0.63258507, 0.02279761])>)

## 2. Find the shape, rank and size of the tensors you created in 1. 

In [9]:
scalar.shape, scalar.ndim, tf.size(scalar)

(TensorShape([]), 0, <tf.Tensor: shape=(), dtype=int32, numpy=1>)

In [10]:
vector.shape, vector.ndim, tf.size(vector)

(TensorShape([2]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=2>)

In [12]:
matrix.shape, matrix.ndim, tf.size(matrix)

(TensorShape([2, 2]), 2, <tf.Tensor: shape=(), dtype=int32, numpy=4>)

In [11]:
tensor.shape, tensor.ndim, tf.size(tensor)

(TensorShape([50]), 1, <tf.Tensor: shape=(), dtype=int32, numpy=50>)

## 3. Create 2 tensors with random values between 0 and 1 with shape [5, 300]

In [22]:
t1 = tf.constant(value=np.random.random(size=1500), shape=[5, 300])
t1

<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
array([[0.73648947, 0.25068335, 0.66075995, ..., 0.25126419, 0.15631105,
        0.98072027],
       [0.96950929, 0.02610382, 0.39090389, ..., 0.91460655, 0.30235123,
        0.47540495],
       [0.06933372, 0.79240239, 0.30564182, ..., 0.95940976, 0.9945395 ,
        0.28805234],
       [0.27012156, 0.41015172, 0.49768206, ..., 0.99255173, 0.21342994,
        0.44504157],
       [0.91542562, 0.72681432, 0.89765909, ..., 0.50741191, 0.37439033,
        0.50901612]])>

In [20]:
t2 = tf.constant(value=np.random.random(size=1500), shape=[5, 300])
t2

<tf.Tensor: shape=(5, 300), dtype=float64, numpy=
array([[0.19360944, 0.5281249 , 0.06928491, ..., 0.20798906, 0.59639828,
        0.75513541],
       [0.35756266, 0.01716071, 0.21272551, ..., 0.07043848, 0.57303946,
        0.60167435],
       [0.3523377 , 0.17394543, 0.15320322, ..., 0.54463234, 0.59412868,
        0.67372509],
       [0.45303478, 0.91197832, 0.72407639, ..., 0.2551976 , 0.72207904,
        0.63315049],
       [0.35965386, 0.09034326, 0.51591915, ..., 0.81096698, 0.03838016,
        0.7708476 ]])>

## 4. Multiply the two tensors you created using matrix multiplication

In [28]:
tf.matmul(t1, tf.transpose(t2))

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[81.59563764, 78.47526259, 80.37877549, 76.64890425, 79.87358855],
       [80.77161457, 75.66856553, 76.63893694, 74.64157822, 80.33962572],
       [86.53699818, 80.97042032, 86.17675834, 78.23292954, 82.64307179],
       [78.92695632, 77.89194313, 80.79005179, 74.57013788, 79.05376563],
       [81.03230448, 78.64504796, 77.65747308, 75.47843155, 75.8110577 ]])>

## 5. Multiply the two tensors you created using dot product

In [30]:
tf.tensordot(t1, tf.transpose(t2), axes=1)

<tf.Tensor: shape=(5, 5), dtype=float64, numpy=
array([[81.59563764, 78.47526259, 80.37877549, 76.64890425, 79.87358855],
       [80.77161457, 75.66856553, 76.63893694, 74.64157822, 80.33962572],
       [86.53699818, 80.97042032, 86.17675834, 78.23292954, 82.64307179],
       [78.92695632, 77.89194313, 80.79005179, 74.57013788, 79.05376563],
       [81.03230448, 78.64504796, 77.65747308, 75.47843155, 75.8110577 ]])>

## 6. Create a tensor with random values between 0 and 1 with shape [224, 224, 3].

In [31]:
t3 = tf.constant(np.random.random(size=150528), shape=[224, 224, 3])
t3

<tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
array([[[0.77872496, 0.28884532, 0.34831453],
        [0.38906093, 0.1596622 , 0.25883319],
        [0.48808099, 0.04303483, 0.6526702 ],
        ...,
        [0.23200718, 0.66341881, 0.8506651 ],
        [0.43001156, 0.57236786, 0.6920197 ],
        [0.49121047, 0.24743613, 0.19385103]],

       [[0.84756764, 0.8126201 , 0.97785407],
        [0.26320304, 0.03664559, 0.70649506],
        [0.57661188, 0.86325897, 0.61192327],
        ...,
        [0.77485051, 0.754348  , 0.9185109 ],
        [0.38773963, 0.1463581 , 0.29258257],
        [0.37071823, 0.11464138, 0.72118043]],

       [[0.11856434, 0.98664312, 0.73283055],
        [0.97492783, 0.77708531, 0.82987592],
        [0.80961979, 0.34580421, 0.97320555],
        ...,
        [0.73614578, 0.9169964 , 0.84254675],
        [0.65818338, 0.19902617, 0.97853932],
        [0.7138829 , 0.4737798 , 0.44564614]],

       ...,

       [[0.28603949, 0.03537479, 0.51643091],
        [0.81

## 7. Find the min and max values of the tensor you created in 6.

In [33]:
tf.reduce_max(t3)

<tf.Tensor: shape=(), dtype=float64, numpy=0.9999975883042053>

In [34]:
tf.reduce_min(t3)

<tf.Tensor: shape=(), dtype=float64, numpy=5.720777317974601e-06>

## 8. Created a tensor with random values of shape [1, 224, 224, 3] then squeeze it to change the shape to [224, 224, 3].

In [36]:
t4 = tf.constant(np.random.random(size=150528), shape=[1, 224, 224, 3])
t4

<tf.Tensor: shape=(1, 224, 224, 3), dtype=float64, numpy=
array([[[[0.49834138, 0.998955  , 0.11939424],
         [0.81097368, 0.29030459, 0.28439257],
         [0.4396371 , 0.471556  , 0.62474628],
         ...,
         [0.94691576, 0.65759733, 0.58378146],
         [0.65154854, 0.66802436, 0.03408876],
         [0.96438534, 0.7665123 , 0.16389252]],

        [[0.88397555, 0.195361  , 0.89312951],
         [0.4878915 , 0.4470219 , 0.43626604],
         [0.89257875, 0.41298086, 0.80872525],
         ...,
         [0.17817951, 0.15872377, 0.79421703],
         [0.33105671, 0.83630052, 0.93619455],
         [0.63084853, 0.80678245, 0.120445  ]],

        [[0.44567817, 0.15695307, 0.66904162],
         [0.65051353, 0.81024939, 0.79542675],
         [0.01182546, 0.54783557, 0.26616563],
         ...,
         [0.4340995 , 0.86955217, 0.36028708],
         [0.79953371, 0.60578033, 0.79674685],
         [0.48990977, 0.10431125, 0.03307492]],

        ...,

        [[0.33124268, 0.37594689, 

In [38]:
t4_squeezed = tf.squeeze(t4)
t4_squeezed

<tf.Tensor: shape=(224, 224, 3), dtype=float64, numpy=
array([[[0.49834138, 0.998955  , 0.11939424],
        [0.81097368, 0.29030459, 0.28439257],
        [0.4396371 , 0.471556  , 0.62474628],
        ...,
        [0.94691576, 0.65759733, 0.58378146],
        [0.65154854, 0.66802436, 0.03408876],
        [0.96438534, 0.7665123 , 0.16389252]],

       [[0.88397555, 0.195361  , 0.89312951],
        [0.4878915 , 0.4470219 , 0.43626604],
        [0.89257875, 0.41298086, 0.80872525],
        ...,
        [0.17817951, 0.15872377, 0.79421703],
        [0.33105671, 0.83630052, 0.93619455],
        [0.63084853, 0.80678245, 0.120445  ]],

       [[0.44567817, 0.15695307, 0.66904162],
        [0.65051353, 0.81024939, 0.79542675],
        [0.01182546, 0.54783557, 0.26616563],
        ...,
        [0.4340995 , 0.86955217, 0.36028708],
        [0.79953371, 0.60578033, 0.79674685],
        [0.48990977, 0.10431125, 0.03307492]],

       ...,

       [[0.33124268, 0.37594689, 0.07037661],
        [0.89

## 9. Create a tensor with shape [10] using your own choice of values, then find the index which has the maximum value.

In [40]:
t5 = tf.constant(np.random.random(size=5), shape=[5])
t5

<tf.Tensor: shape=(5,), dtype=float64, numpy=array([0.83882851, 0.86100618, 0.42000351, 0.46067794, 0.808897  ])>

In [41]:
tf.argmax(t5)

<tf.Tensor: shape=(), dtype=int64, numpy=1>

## 10. One-hot encode the tensor you created in 9.

In [43]:
# One hot encoding the tensor of shape 10 
tf.one_hot(tf.cast(t5 , dtype=tf.int32) , depth = 5)

<tf.Tensor: shape=(5, 5), dtype=float32, numpy=
array([[1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0.]], dtype=float32)>